# Generated by Django 5.2.7 on 2026-01-09 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_retraininglog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("viewer", "Viewer"),
                            ("consumer", "Consumer"),
                        ],
                        default="consumer",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_view_analytics", models.BooleanField(default=False)),
                ("can_trigger_retraining", models.BooleanField(default=False)),
                ("can_export_data", models.BooleanField(default=False)),
                (
                    "assigned_meter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Meter assigned to this consumer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_users",
                        to="core.meter",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["user__username"],
            },
        ),
    ]
