# Generated by Django 5.2.7 on 2026-01-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("meters_imported", models.IntegerField(default=0)),
                ("records_imported", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Import Log",
                "verbose_name_plural": "Import Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "meter_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("acorn_group", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "acorn_grouped",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("stdorToU", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("file", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Meter",
                "verbose_name_plural": "Meters",
                "ordering": ["meter_id"],
            },
        ),
        migrations.CreateModel(
            name="DailyConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "consumption_data",
                    models.JSONField(
                        help_text="Dictionary with keys hh_0 to hh_47 and consumption values"
                    ),
                ),
                (
                    "total_consumption",
                    models.FloatField(
                        default=0.0, help_text="Sum of 48 half-hour readings"
                    ),
                ),
                (
                    "average_consumption",
                    models.FloatField(default=0.0, help_text="Average of 48 readings"),
                ),
                (
                    "max_consumption",
                    models.FloatField(
                        default=0.0, help_text="Maximum half-hour reading"
                    ),
                ),
                (
                    "min_consumption",
                    models.FloatField(
                        default=0.0, help_text="Minimum half-hour reading"
                    ),
                ),
                (
                    "is_holiday",
                    models.BooleanField(
                        default=False, help_text="Is this day a bank holiday?"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        help_text="Average temperature for the day",
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption",
                        to="core.meter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Consumption",
                "verbose_name_plural": "Daily Consumptions",
                "ordering": ["-date", "meter"],
                "indexes": [
                    models.Index(
                        fields=["meter", "date"], name="core_dailyc_meter_i_a5ac01_idx"
                    ),
                    models.Index(fields=["date"], name="core_dailyc_date_bb1cd0_idx"),
                    models.Index(
                        fields=["total_consumption"],
                        name="core_dailyc_total_c_bfaf0f_idx",
                    ),
                ],
                "unique_together": {("meter", "date")},
            },
        ),
    ]
