# Generated by Django 5.2.7 on 2026-01-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "anomaly_score",
                    models.FloatField(
                        help_text="Negative scores are more anomalous (Isolation Forest)"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("suspicious", "Suspicious"),
                            ("theft", "Theft"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="Confidence in classification (0-1)"
                    ),
                ),
                (
                    "threshold_normal",
                    models.FloatField(help_text="Score > this = Normal"),
                ),
                (
                    "threshold_suspicious",
                    models.FloatField(
                        help_text="Score between thresholds = Suspicious"
                    ),
                ),
                (
                    "threshold_theft",
                    models.FloatField(help_text="Score < this = Theft"),
                ),
                (
                    "peak_hour",
                    models.IntegerField(
                        blank=True,
                        help_text="Hour (0-47) with highest consumption",
                        null=True,
                    ),
                ),
                (
                    "peak_consumption",
                    models.FloatField(
                        blank=True, help_text="Consumption at peak hour", null=True
                    ),
                ),
                (
                    "total_deviation",
                    models.FloatField(
                        blank=True,
                        help_text="Total deviation from expected pattern",
                        null=True,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "model_name",
                    models.CharField(default="IsolationForest", max_length=100),
                ),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_consumption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_results",
                        to="core.dailyconsumption",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_results",
                        to="core.meter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Result",
                "verbose_name_plural": "Anomaly Results",
                "ordering": ["-date", "meter"],
                "indexes": [
                    models.Index(
                        fields=["meter", "date"], name="core_anomal_meter_i_bcac6e_idx"
                    ),
                    models.Index(fields=["date"], name="core_anomal_date_3a5b5f_idx"),
                    models.Index(
                        fields=["classification"], name="core_anomal_classif_286122_idx"
                    ),
                    models.Index(
                        fields=["anomaly_score"], name="core_anomal_anomaly_01cebb_idx"
                    ),
                ],
                "unique_together": {("meter", "date")},
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField(default=1)),
                (
                    "model_name",
                    models.CharField(default="IsolationForest", max_length=100),
                ),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        help_text="Path to .pkl or .joblib file",
                        null=True,
                        upload_to="models/",
                    ),
                ),
                (
                    "scaler_file",
                    models.FileField(
                        blank=True,
                        help_text="Path to scaler .pkl file",
                        null=True,
                        upload_to="scalers/",
                    ),
                ),
                (
                    "window_size",
                    models.IntegerField(default=30, help_text="Days used for training"),
                ),
                (
                    "contamination",
                    models.FloatField(
                        default=0.1, help_text="Expected proportion of outliers"
                    ),
                ),
                ("threshold_normal", models.FloatField(default=0.0)),
                ("threshold_theft", models.FloatField(default=-0.1)),
                ("training_samples", models.IntegerField(default=0)),
                ("validation_accuracy", models.FloatField(blank=True, null=True)),
                ("validation_f1", models.FloatField(blank=True, null=True)),
                ("false_positive_rate", models.FloatField(blank=True, null=True)),
                ("false_negative_rate", models.FloatField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Currently used for predictions"
                    ),
                ),
                ("is_trained", models.BooleanField(default=False)),
                ("trained_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("training_logs", models.JSONField(blank=True, default=dict)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_versions",
                        to="core.meter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Version",
                "verbose_name_plural": "Model Versions",
                "ordering": ["meter", "-version_number"],
                "unique_together": {("meter", "version_number")},
            },
        ),
    ]
