# Generated by Django 5.2.7 on 2026-01-09 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_anomalyresult_modelversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrainingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Description of retraining job", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "meters_processed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of meter IDs processed",
                    ),
                ),
                (
                    "meters_success",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of meter IDs where retraining succeeded",
                    ),
                ),
                (
                    "meters_failed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of meter IDs where retraining failed",
                    ),
                ),
                (
                    "meters_improved",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of meter IDs where performance improved ≥5%",
                    ),
                ),
                (
                    "meters_unchanged",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of meter IDs where performance improved <5%",
                    ),
                ),
                ("total_meters", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("improved_count", models.IntegerField(default=0)),
                ("unchanged_count", models.IntegerField(default=0)),
                (
                    "average_improvement",
                    models.FloatField(
                        default=0.0,
                        help_text="Average performance improvement across all meters",
                    ),
                ),
                (
                    "window_days",
                    models.IntegerField(default=30, help_text="Days used for training"),
                ),
                (
                    "validation_days",
                    models.IntegerField(
                        default=7, help_text="Days used for validation"
                    ),
                ),
                (
                    "improvement_threshold",
                    models.FloatField(
                        default=5.0,
                        help_text="Minimum improvement required to replace model (%)",
                    ),
                ),
                (
                    "detailed_logs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Detailed logs for each meter",
                    ),
                ),
                (
                    "error_logs",
                    models.TextField(blank=True, help_text="Error messages if any"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retraining_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Retraining Log",
                "verbose_name_plural": "Retraining Logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
