# Generated by Django 5.2.7 on 2026-01-09 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_retraininglog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulation_speed",
                    models.IntegerField(
                        default=1,
                        help_text="How many half-hours to advance per page load",
                    ),
                ),
                (
                    "current_pointer",
                    models.IntegerField(
                        default=0, help_text="Current position in historical data"
                    ),
                ),
                ("is_simulation_active", models.BooleanField(default=True)),
                (
                    "chart_theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("colorblind", "Colorblind Friendly"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to="core.meter",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="HalfHourReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("consumption", models.FloatField()),
                ("hour", models.IntegerField(help_text="Hour of day (0-23)")),
                ("minute", models.IntegerField(help_text="Minute (0 or 30)")),
                ("is_peak", models.BooleanField(default=False)),
                ("is_off_peak", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anomaly_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="half_hour_readings",
                        to="core.anomalyresult",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="half_hour_readings",
                        to="core.meter",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Half Hour Reading",
                "verbose_name_plural": "Half Hour Readings",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["meter", "timestamp"],
                        name="core_halfho_meter_i_0c066e_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="core_halfho_timesta_e208b7_idx"
                    ),
                ],
            },
        ),
    ]
