# Generated by Django 5.2.7 on 2026-01-09 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile_halfhourreading"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_classification",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("suspicious", "Suspicious"),
                            ("theft", "Theft"),
                        ],
                        help_text="Original model prediction",
                        max_length=20,
                    ),
                ),
                (
                    "override_classification",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("suspicious", "Suspicious"),
                            ("theft", "Theft"),
                        ],
                        help_text="Admin override value",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for override (e.g., field inspection, meter fault)",
                        null=True,
                    ),
                ),
                ("overridden_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified_by_field", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True, null=True)),
                (
                    "anomaly_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_override",
                        to="core.anomalyresult",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomaly_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Override",
                "verbose_name_plural": "Admin Overrides",
                "ordering": ["-overridden_at"],
            },
        ),
    ]
