# Generated by Django 5.2.7 on 2026-01-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_adminoverride"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminOverride",
        ),
    ]
