# Generated by Django 5.2.7 on 2026-01-11 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delete_adminoverride"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalyresult",
            name="injection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for injection if applicable"
            ),
        ),
        migrations.AddField(
            model_name="anomalyresult",
            name="is_injected",
            field=models.BooleanField(
                default=False, help_text="Whether this result was manually injected"
            ),
        ),
        migrations.CreateModel(
            name="AnomalyInjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("full_day", "Full Day"),
                            ("00:00", "00:00-00:30"),
                            ("00:30", "00:30-01:00"),
                            ("01:00", "01:00-01:30"),
                            ("01:30", "01:30-02:00"),
                            ("02:00", "02:00-02:30"),
                            ("02:30", "02:30-03:00"),
                            ("03:00", "03:00-03:30"),
                            ("03:30", "03:30-04:00"),
                            ("04:00", "04:00-04:30"),
                            ("04:30", "04:30-05:00"),
                            ("05:00", "05:00-05:30"),
                            ("05:30", "05:30-06:00"),
                            ("06:00", "06:00-06:30"),
                            ("06:30", "06:30-07:00"),
                            ("07:00", "07:00-07:30"),
                            ("07:30", "07:30-08:00"),
                            ("08:00", "08:00-08:30"),
                            ("08:30", "08:30-09:00"),
                            ("09:00", "09:00-09:30"),
                            ("09:30", "09:30-10:00"),
                            ("10:00", "10:00-10:30"),
                            ("10:30", "10:30-11:00"),
                            ("11:00", "11:00-11:30"),
                            ("11:30", "11:30-12:00"),
                            ("12:00", "12:00-12:30"),
                            ("12:30", "12:30-13:00"),
                            ("13:00", "13:00-13:30"),
                            ("13:30", "13:30-14:00"),
                            ("14:00", "14:00-14:30"),
                            ("14:30", "14:30-15:00"),
                            ("15:00", "15:00-15:30"),
                            ("15:30", "15:30-16:00"),
                            ("16:00", "16:00-16:30"),
                            ("16:30", "16:30-17:00"),
                            ("17:00", "17:00-17:30"),
                            ("17:30", "17:30-18:00"),
                            ("18:00", "18:00-18:30"),
                            ("18:30", "18:30-19:00"),
                            ("19:00", "19:00-19:30"),
                            ("19:30", "19:30-20:00"),
                            ("20:00", "20:00-20:30"),
                            ("20:30", "20:30-21:00"),
                            ("21:00", "21:00-21:30"),
                            ("21:30", "21:30-22:00"),
                            ("22:00", "22:00-22:30"),
                            ("22:30", "22:30-23:00"),
                            ("23:00", "23:00-23:30"),
                            ("23:30", "23:30-00:00"),
                        ],
                        default="full_day",
                        help_text="Specific 30-minute slot or full day",
                        max_length=10,
                    ),
                ),
                (
                    "injection_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("suspicious", "Suspicious"),
                            ("theft", "Theft"),
                        ],
                        help_text="Classification to inject",
                        max_length=20,
                    ),
                ),
                (
                    "injected_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Anomaly score to inject (use typical values: Normal>0.1, Suspicious=0.0, Theft<-0.1)",
                    ),
                ),
                (
                    "injected_confidence",
                    models.FloatField(
                        default=0.95, help_text="Confidence for injection (0-1)"
                    ),
                ),
                (
                    "consumption_override",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Override consumption for the time slot (e.g., {"value": 2.5})',
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text='Reason for injection (e.g., "Scheduled maintenance", "Known theft case")',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this injection is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Automatic deactivation date (optional)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_injections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injections",
                        to="core.meter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Injection",
                "verbose_name_plural": "Anomaly Injections",
                "ordering": ["-date", "meter", "time_slot"],
                "unique_together": {("meter", "date", "time_slot")},
            },
        ),
        migrations.AddField(
            model_name="anomalyresult",
            name="injection_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_results",
                to="core.anomalyinjection",
            ),
        ),
    ]
