# Generated by Django 4.2.7 on 2026-01-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="is_resolved",
        ),
        migrations.AddField(
            model_name="feedback",
            name="admin_response",
            field=models.TextField(
                blank=True, help_text="Admin's response to feedback", null=True
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "🟡 Pending"),
                    ("investigation", "🔍 Under Investigation"),
                    ("completed", "✅ Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
