# Generated by Django 4.2.7 on 2026-01-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_feedback_is_resolved_feedback_admin_response_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "⏳ Pending"),
                    ("investigation", "🔍 Under Investigation"),
                    ("completed", "✅ Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="core.meter",
            ),
        ),
    ]
