# Generated by Django 4.2.7 on 2026-01-20 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_alter_feedback_options_feedback_is_resolved_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={},
        ),
        migrations.AddField(
            model_name="feedback",
            name="meter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="core.meter",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="admin_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
